### PR TITLE
Support for Rails 4.2 and bump version

### PR DESCRIPTION
**Pull request by dgilperez**
Cheers!

### CODE REVIEW

**Comment by dgilperez** [comment]
Hey @mjc, any change to get this merged anytime soon? Thanks!

**Comment by dgilperez** [comment]
Great! Thanks :+1:

**Comment by dgilperez** [comment]
Could you please push it to rubygems? Thanks!

**Comment by mjc** [comment]
Done, sorry about that.

**Comment by dgilperez** [comment]
Thanks!!!!

**Pull request merged**
